// NET7_Auth/SpaCookieAuthentication/a.Together/reactjs/src/App.js
import logo from './logo.svg';
import './App.css';
import user from './init-user'

function App() {
    const login = () => fetch('/api/login', {method: 'post'})
    const test = () => fetch('/api/test')
    return (
        <div className="App">
            <button onClick={login}>Login</button>
            <button onClick={test}>Test</button>
            <span>{user['username']}</span>
        </div>
    );
}

export default App;

// NET7_Auth/SpaCookieAuthentication/c.SsrFramework/nuxt3/app.vue
<template>
  <div>
    <button @click="login">Login</button>
    <button @click="test">Test</button>
  </div>
</template>

<script setup>
const login = () => fetch('https://localhost:5111/api/login', {method: 'post', credentials: 'include'})
const test = () => fetch('https://localhost:5111/api/test', {credentials: 'include'})
</script>
